version: 0.0
os: linux
files:
  - source: /
    destination: /home/ssm-user/plumcommerce_old # 🌟 실제 작동 경로로 변경
    file_exists_behavior: OVERWRITE # 🌟 files 블록과 들여쓰기 라인 정렬 (오류 수정)
permissions:
  - object: /home/ssm-user/plumcommerce_old # 🌟 실제 작동 경로로 변경
    pattern: "**"
    owner: ssm-user # 🌟 현재 EC2 계정인 ssm-user로 변경
    group: ssm-user # 🌟 현재 EC2 계정인 ssm-user로 변경
hooks:
  BeforeInstall:
    - location: scripts/codedeploy_stop.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/codedeploy_install.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/codedeploy_start.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/codedeploy_validate.sh
      timeout: 60
      runas: root
